apiVersion: v1
kind: Namespace
metadata:
  name: argocd-sp-controller
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: argocd-sp-controller
  namespace: argocd-sp-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-sp-controller
  namespace: argocd-sp-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: argocd-sp-controller
  template:
    metadata:
      labels:
        application: argocd-sp-controller
    spec:
      serviceAccountName: argocd-sp-controller
      containers:
        - name: argocd-sp-controller
          image: k8sware/argocdsp:latest
          imagePullPolicy: Always
          livelinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
